- name: List all kops clusters
  hosts: localhost
  vars_files:
    - variables.yml
    - secret.yaml
  tasks:
    - name: Set kops path for Linux
      set_fact:
        kops_path: "/usr/local/bin/kops"
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - name: Set kops path for macOS
      set_fact:
        kops_path: "/opt/homebrew/bin/kops"
      when: ansible_distribution == 'MacOSX'
    - name: Run kops get clusters to list all clusters
      command:
        cmd: "{{ kops_path }} get clusters --state s3://{{ s3name}} "
      register: clusters_output

    - name: Display all clusters
      debug:
        msg: "{{ clusters_output.stdout_lines }}"
